# Docker Compose configuration for kiisrv using Docker Hub images
# Use this on IPv6-only servers where ghcr.io doesn't work
#
# To use with your fork:
#   1. Replace 'your-dockerhub-username' with your Docker Hub username throughout this file
#   2. Replace 'latest' with your tag (e.g., 'containerize', 'v1.0.0') if needed
#   3. Find your docker GID: getent group docker | cut -d: -f3
#   4. Update the group_add section below with your docker GID
#
# Usage Option A (Automated - Recommended):
#   # Pull only controller-057 (latest, fastest - recommended)
#   ./pull-and-tag.sh compose.dockerhub.yaml your-dockerhub-username containerize
#   docker compose -f compose.dockerhub.yaml up -d
#
#   # Or pull all controllers (if you need LTS or older versions)
#   ./pull-and-tag.sh compose.dockerhub.yaml your-dockerhub-username containerize all
#   docker compose -f compose.dockerhub.yaml up -d
#
#   # Or pull specific controllers only
#   ./pull-and-tag.sh compose.dockerhub.yaml your-dockerhub-username containerize "050 057"
#   docker compose -f compose.dockerhub.yaml up -d
#
# Usage Option B (Manual):
#   docker compose -f compose.dockerhub.yaml pull
#   # Then manually tag images (see pull-and-tag.sh for commands)
#   docker compose -f compose.dockerhub.yaml up -d
#
# NOTE: kiisrv expects images named 'kiisrv-controller-057:latest' (without registry prefix).
# The pull-and-tag.sh script handles this automatically.

services:
  kiisrv:
    image: your-dockerhub-username/kiisrv-kiisrv:latest
    container_name: kiisrv
    
    # Docker socket permissions: Add docker group to container user
    # This allows kiisrv to spawn controller containers
    # Find your GID with: getent group docker | cut -d: -f3
    # Common values: 999 (Debian/Ubuntu), 998 (some systems)
    group_add:
      - "999"  # IMPORTANT: Replace with your actual docker group GID
    
    ports:
      - "${KIISRV_PORT:-3001}:3001"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.db:/app/config.db
      - ./stats.db:/app/stats.db
      - ./tmp_builds:/app/tmp_builds
      - ./tmp_config:/app/tmp_config
      # Optional: Mount apikey file if you have a GitHub token (uncomment if you created the file)
      # - ./apikey:/app/apikey:ro
      # Optional: Mount custom layouts (uncomment if you want to override built-in layouts)
      # - ./layouts:/app/layouts:ro
    
    environment:
      - KIISRV_HOST=0.0.0.0
      - KIISRV_PORT=3001
      # Uncomment for detailed logging/debugging:
      # - RUST_LOG=debug
      - HOST_TMP_CONFIG=${PWD}/tmp_config
      - HOST_TMP_BUILDS=${PWD}/tmp_builds
    
    networks:
      - kiisrv
    restart: unless-stopped

  # Controller images (used by kiisrv, not started directly)
  # These have profile: manual so they won't start with 'up'
  # kiisrv spawns them dynamically via Docker socket

  controller-050:
    image: your-dockerhub-username/kiisrv-controller-050:latest
    profiles:
      - manual
    networks:
      - kiisrv

  controller-054:
    image: your-dockerhub-username/kiisrv-controller-054:latest
    profiles:
      - manual
    networks:
      - kiisrv

  controller-055:
    image: your-dockerhub-username/kiisrv-controller-055:latest
    profiles:
      - manual
    networks:
      - kiisrv

  controller-056:
    image: your-dockerhub-username/kiisrv-controller-056:latest
    profiles:
      - manual
    networks:
      - kiisrv

  controller-057:
    image: your-dockerhub-username/kiisrv-controller-057:latest
    profiles:
      - manual
    networks:
      - kiisrv

networks:
  kiisrv:
    driver: bridge

